anypet/Models/Association.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AdoptNet.Models;
using System.ComponentModel.DataAnnotations.Schema;


namespace anypet.Models
{
    public class Association
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [RegularExpression(@"^[a-zA-Z_ ]+$", ErrorMessage = "The name must contain only letters...")]
        [Required(ErrorMessage = "You must input Name of the Association")]
        public String Name { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Association Phone")]
        public long PhoneNumber { get; set; }

        [Display(Name = "Association Location")]
        public String Location { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Association Email")]
        [Required(ErrorMessage = "You must input Email of the Association")]
        public String EmailOfUser { get; set; }

        //this field represnt the connection of many to one 

        public List<Animal> Animals { get; set; }

        public AssociationImages AssociationImage { get; set; }

        //this field represent the connection of many to many 
        public List<AdoptionDays> AdoptionDays { get; set; }



    }
}

anypet/Controllers/AssociationImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using anypet.Models;

namespace anypet.Controllers
{
    public class AssociationImagesController : Controller
    {
        private readonly AdoptNetContext _context;

        public AssociationImagesController(AdoptNetContext context)
        {
            _context = context;
        }




        // GET: AssociationImages/Create
        public IActionResult Create()
        {
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name));
            return View();
        }

        // POST: AssociationImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Image,AssociationId")] AssociationImages associationImages)
        {
            if (ModelState.IsValid)
            {
                var check = _context.AssociationImages.Where(r => r.AssociationId.Equals(associationImages.AssociationId));

                if (check.Count() == 0)
                {
                    _context.Add(associationImages);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), "Associations");
                }
                else
                {
                    ViewData["Error"] = "this Association allready  have an image";
                }
            }
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name));
            return View(associationImages);
        }

        // GET: AssociationImages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var associationImages = await _context.AssociationImages.FindAsync(id);
            if (associationImages == null)
            {
                return NotFound();
            }
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name), associationImages.AssociationId);
            return View(associationImages);
        }

        // POST: AssociationImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Image,AssociationId")] AssociationImages associationImages)
        {
            if (id != associationImages.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(associationImages);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssociationImagesExists(associationImages.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Associations");
            }
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name), associationImages.AssociationId);
            return View(associationImages);
        }

        // GET: AssociationImages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var associationImages = await _context.AssociationImages
                .Include(a => a.Association)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (associationImages == null)
            {
                return NotFound();
            }

            return View(associationImages);
        }

        // POST: AssociationImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var associationImages = await _context.AssociationImages.FindAsync(id);
            _context.AssociationImages.Remove(associationImages);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Associations");
        }

        private bool AssociationImagesExists(int id)
        {
            return _context.AssociationImages.Any(e => e.Id == id);
        }
    }
}

anypet/Controllers/AssociationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using anypet.Models;
using Microsoft.AspNetCore.Authorization;
using AdoptNet.Models;

namespace AdoptNet.Controllers
{
    public class AssociationsController : Controller
    {
        private readonly AdoptNetContext _context;

        public AssociationsController(AdoptNetContext context)
        {
            _context = context;



        }


        // GET: Associations
        // The connection between many to many -> adoption days and associations
        // one to one -> each association has it own image
        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> Index()
        {
            var adoptNetContext = _context.Association.Include(a => a.AssociationImage).Include(a => a.AdoptionDays);
            return View(await adoptNetContext.ToListAsync());
        }
        // GET: Associations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var association = await _context.Association.Include(a => a.AdoptionDays)
                .FirstOrDefaultAsync(m => m.Id == id);
            var adoptionday = await _context.AdoptionDays
               .FirstOrDefaultAsync(m => m.Id == id);
            if (association == null)
            {
                return NotFound();
            }
            return View(association);
        }

        // GET: Associations/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["Adoption"] = new SelectList(_context.AdoptionDays, "Id", "Name");
            return View();
        }

        // many to many - creating new association and allocating memory to adoption days to each association
        // this connecting is also shows in the adoption days
        // POST: Associations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PhoneNumber,Location,EmailOfUser")] Association association, int[] AdoptionDays)
        {
            if (ModelState.IsValid)
            {

                association.AdoptionDays = new List<AdoptionDays>();
                association.AdoptionDays.AddRange(_context.AdoptionDays.Where(x => AdoptionDays.Contains(x.Id)));


                _context.Association.Add(association);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Adoption"] = new SelectList(_context.AdoptionDays, "Id", "Name");
            return View(association);
        }



        public async Task<IActionResult> Search(String Searching)
        {  // Use LINQ to get list of genres.

            var adoptionDays = _context.Association.Include(a => a.Animals).Include(b => b.AssociationImage).Include(c => c.AdoptionDays).Where(b => (b.Name.Contains(Searching) || Searching == null) || (b.Location.Contains(Searching) || Searching == null));
            return View("Index", await adoptionDays.ToListAsync());
        }


        // GET: Associations/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var association = await _context.Association.FindAsync(id);

            if (association == null)
            {
                return NotFound();
            }
            ViewData["Adoption"] = new SelectList(_context.AdoptionDays, "Id", "Name");

            return View(association);
        }
        // POST: Associations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,PhoneNumber,Location,EmailOfUser")] Association association, int[] AdoptionDays)
        {
            if (id != association.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                try
                {
                    Association adoptNetContext = (Association)_context.Association.Include(a => a.AdoptionDays).Where(r => r.Id == id).FirstOrDefault();
                    adoptNetContext.Animals = association.Animals;
                    adoptNetContext.AssociationImage = association.AssociationImage;
                    adoptNetContext.EmailOfUser = association.EmailOfUser;
                    adoptNetContext.Location = association.Location;
                    adoptNetContext.Name = association.Name;
                    adoptNetContext.PhoneNumber = association.PhoneNumber;

                    if (AdoptionDays.Length > 0)
                    {
                        for (int i = 0; i < AdoptionDays.Length; i++)
                        {
                            AdoptionDays adopt = _context.AdoptionDays.Single(n => n.Id == AdoptionDays[i]);

                            if (adoptNetContext.AdoptionDays.Contains(adopt))
                            {
                                ViewData["Error"] = "this Association allready  have this Adoption day  ";
                                ViewData["Adoption"] = new SelectList(_context.AdoptionDays, "Id", "Name");
                                return View(adoptNetContext);

                            }
                            else
                            {
                                adoptNetContext.AdoptionDays.Add(adopt);
                                _context.Update(adoptNetContext);
                                await _context.SaveChangesAsync();
                            }


                        }
                    }
                    else if (AdoptionDays.Length == 0)
                    {
                        _context.Update(adoptNetContext);
                        await _context.SaveChangesAsync();

                    }

                    else
                    {
                        adoptNetContext.AdoptionDays = new List<AdoptionDays>();
                        adoptNetContext.AdoptionDays.AddRange(_context.AdoptionDays.Where(x => AdoptionDays.Contains(x.Id)));
                        _context.Update(adoptNetContext);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!AssociationExists(association.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Adoption"] = new SelectList(_context.AdoptionDays, "Id", "Name");
            return View(association);
        }

        // GET: Associations/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var association = await _context.Association
                .FirstOrDefaultAsync(m => m.Id == id);
            if (association == null)
            {
                return NotFound();
            }
            return View(association);
        }
        // POST: Associations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var association = await _context.Association.FindAsync(id);
            _context.Association.Remove(association);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool AssociationExists(int id)
        {
            return _context.Association.Any(e => e.Id == id);
        }

        public JsonResult GetAssociationPlace()
        {
            List<Association> AssociationList = new List<Association>();
            foreach (var item in _context.Association)
            {
                AssociationList.Add(item);

            }
            return Json(AssociationList);
        }

        //graph1
        public JsonResult GetAnimalsCount()
        {
            List<String> Res = new List<String>();
            int AmountOfDogs = _context.Animal.Where(a => a.Kind == Kind.Dog).Count();
            int AmountOfCats = _context.Animal.Where(a => a.Kind == Kind.Cat).Count();

            Res.Add(AmountOfCats.ToString());
            Res.Add(AmountOfDogs.ToString());

            return Json(Res);
        }

    }
}

anypet/Views/Associations/Create.cshtml
@model anypet.Models.Association

@{ ViewData["Title"] = "Create"; }
<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>
<br />

<h1><ins>Adding a new Association</ins></h1>
<hr />

<div class="row justify-content-center">
    <div class="col-md-3 formback">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmailOfUser" class="control-label"></label>
                <input asp-for="EmailOfUser" class="form-control" />
                <span asp-validation-for="EmailOfUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdoptionDays" class="control-label"></label>
                <select asp-for="AdoptionDays" class="form-control" asp-items="ViewBag.Adoption"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-dark inputspace subotton" />
                <a asp-action="Index"><input value="List" class="btn btn-outline-dark inputspace subotton " /></a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

anypet/Views/Associations/Delete.cshtml
@model anypet.Models.Association

@{ ViewData["Title"] = "Delete"; }

<!-- Button trigger modal -->
<button type="button" data-toggle="modal" data-target="#exampleModal"
        style="margin-left:45%; margin-top: 120px;">
    Delete an association
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="column" id="main">
                    <h1 class="deletePopup">
                        Are you sure you want to delete this association?
                    </h1>
                    <br />
                    <dl class="row">
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.PhoneNumber)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Location)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Location)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.EmailOfUser)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.EmailOfUser)
                        </dd>
                    </dl>
                    <form asp-action="Delete" style="font-size: .8em;">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <<a asp-controller="Associations" asp-action="Index">Back to List</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

anypet/Views/Associations/Details.cshtml
@model anypet.Models.Association

@{
    ViewData["Title"] = "Details";
}

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>

<h1>Details of an Animal</h1>

<details>
    <summary class="background" >@Html.DisplayFor(model => model.Name)</summary>
    <div class="content">
        <dt class="col-6 mx-auto spacesdes">
            <h5>
                <u>@Html.DisplayNameFor(model => model.Name):</u>
            </h5>
        </dt>
        <dd class="col-6 mx-auto spacesdes">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-6 mx-auto spacesdes">
            <h5><u> @Html.DisplayNameFor(model => model.PhoneNumber):</u> </h5>
        </dt>
        <dd class="col-6 mx-auto spacesdes">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-6 mx-auto spacesdes">
            <h5><u>@Html.DisplayNameFor(model => model.EmailOfUser):</u>  </h5>
        </dt>
        <dd class="col-6 mx-auto spacesdes">
            @Html.DisplayFor(model => model.EmailOfUser)
        </dd>
        <dt class="col-6 mx-auto spacesdes">
            <h5><u>@Html.DisplayNameFor(model => model.Location):</u> </h5>
        </dt>
        <dd class="col-6 mx-auto spacesdes">
            @Html.DisplayFor(model => model.Location)
        </dd>
       
        <form class="col-6 mx-auto spacesdes" id="footerbootom">
            <input type="hidden" asp-for="Id" />
            <a asp-action="Index"><input value="List" class="btn btn-outline-dark inputspace subotton " /></a>
        </form>
    </div>
</details>

anypet/Views/Associations/Index.cshtml
@model IEnumerable<anypet.Models.Association>

@{ ViewData["Title"] = "Index"; }

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">

</head>

<header class="jumbotron bg-cover text-white image">

    <div class="container py-5 text-center">
        <h2 class="display-4 font-weight-bold">Associations</h2>
    </div>

</header>

@if (ViewContext.HttpContext.User.IsInRole("Admin"))
{
<a asp-action="Create"><input value="Add-Association" style="width:155px;" class="btn btn-outline-dark subotton mix" /></a>}

<div style="text-align: center; margin-right: -80px;">
    <form asp-controller="Associations" asp-action="Search">
        <input name="Searching" placeholder="Enter something to search" />
        <input type="submit" value="Search" class="btn btn-outline-dark subotton"
               style="height:40px; margin-bottom: 15px;" />
    </form>
</div>

<div class="form-group ">

</div>
<div class="row">

    @foreach (var Association in Model)
    {
<div class="col-md-3 ">
    <div class="card spaceCards spceseColor" style="width: 23rem;">

        @if (Association.AssociationImage != null)
        {
<img src="@Association.AssociationImage.Image" class="card-img-top" alt="...">}

        <div class="card-body">
            <h3 class="card-title boldt ">@Association.Name</h3>
            @if (ViewContext.HttpContext.User.IsInRole("Admin"))
            {

<a class="decoText" asp-action="Edit" asp-route-id="@Association.Id">Edit</a> <i>|</i>
                    <a class="decoText" asp-action="Details" asp-route-id="@Association.Id">Details</a> <i>|</i>
                                        <a class="decoText" asp-action="Delete" asp-route-id="@Association.Id">Delete</a> <i>|</i>
                                                            @if (Association.AssociationImage == null)
                                                            {
                                        <a class="decoText" asp-controller="AssociationImages" asp-action="Create">Add-Image</a>} <i>|</i>
                                                                                @if (Association.AssociationImage != null)
                                                                                {
                                                            <a class="decoText" asp-controller="AssociationImages" asp-action="Edit" asp-route-id="@Association.AssociationImage.Id">Edit Image</a>} <i>|</i>
                                                                                                    @if (Association.AssociationImage != null)
                                                                                                    {
                                                                                <a class="decoText" asp-controller="AssociationImages" asp-action="Delete" asp-route-id="@Association.AssociationImage.Id">Delete Image</a>}}

            <ul class="list-group colorCol list-group-flush">
                <li class="list-group-item list-group-item-danger">Location: @Association.Location</li>
                <li class="list-group-item list-group-item-danger">Phone number: @Association.PhoneNumber</li>
                <li class="list-group-item list-group-item-danger">Email: @Association.EmailOfUser</li>
                <li class="list-group-item list-group-item-danger">
                    Adoption Days:<br />
                    @for (int i = 0; i < Association.AdoptionDays.Count; i++)
                    {
                      @Association.AdoptionDays[i].Name<br />}

                </li>
            </ul>
        </div>

    </div>
</div>}


</div>