anypet/Models/AdoptionDays.cs
using anypet.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AdoptNet.Models
{

    //this class represent the adoption days and its fields
    public class AdoptionDays
    {
        [RegularExpression(@"^[a-zA-Z\s ]+$", ErrorMessage = "The Name must contain only letters...")]
        [Required(ErrorMessage = "You must input Name of the Adoption Day")]
        public String Name { get; set; }
        public int Id { get; set; }

        [Display(Name = "Adoption Day")]
        public DateTime AdoptionDate { get; set; }

        [RegularExpression(@"^[a-zA-Z\s ]+$", ErrorMessage = "The Description must contain only letters...")]
        public String Description { get; set; }

        //this field represent the connection of many to many 
        public List<Association> Associations { get; set; }

        [Display(Name = "Location of the Adoption Day")]
        public Location LocationAdopt { get; set; }



    }
}

anypet/Controllers/AdoptionDaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using AdoptNet.Models;
using Microsoft.AspNetCore.Authorization;

namespace AdoptNet.Controllers
{
    public class AdoptionDaysController : Controller
    {
        private readonly AdoptNetContext _context;

        public AdoptionDaysController(AdoptNetContext context)
        {
            _context = context;
        }

        // GET: AdoptionDays
        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.AdoptionDays.ToListAsync());
        }



        // GET: AdoptionDays/Create
        [Authorize(Roles = "Admin,Association")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdoptionDays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id,AdoptionDate,LocationAdopt,Description")] AdoptionDays adoptionDays)
        {
            if (ModelState.IsValid)
            {
                _context.Add(adoptionDays);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(adoptionDays);
        }




        public async Task<IActionResult> Search(String Searching)
        {  // Use LINQ to get list of genres.

            var adoptionDays = _context.AdoptionDays.Include(a => a.Associations).Where(b => (b.Name.Contains(Searching) || Searching == null) || (b.Description.Contains(Searching) || Searching == null));

            return View("Index", await adoptionDays.ToListAsync());
        }





        // GET: AdoptionDays/Edit/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptionDays = await _context.AdoptionDays.FindAsync(id);
            if (adoptionDays == null)
            {
                return NotFound();
            }
            return View(adoptionDays);
        }

        // POST: AdoptionDays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,AdoptionDate,LocationAdopt,Description")] AdoptionDays adoptionDays)
        {
            if (id != adoptionDays.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adoptionDays);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdoptionDaysExists(adoptionDays.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(adoptionDays);
        }

        // GET: AdoptionDays/Delete/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptionDays = await _context.AdoptionDays
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adoptionDays == null)
            {
                return NotFound();
            }

            return View(adoptionDays);
        }

        // POST: AdoptionDays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adoptionDays = await _context.AdoptionDays.FindAsync(id);
            _context.AdoptionDays.Remove(adoptionDays);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdoptionDaysExists(int id)
        {
            return _context.AdoptionDays.Any(e => e.Id == id);
        }

        public JsonResult GetAdoptDayCount()
        {
            List<String> Res = new List<String>();

            int AmountOfJan = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 1).Count();
            int AmountOfFeb = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 2).Count();
            int AmountOfMar = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 3).Count();
            int AmountOfApr = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 4).Count();
            int AmountOfMay = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 5).Count();
            int AmountOfJun = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 6).Count();
            int AmountOfJul = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 7).Count();
            int AmountOfAug = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 8).Count();
            int AmountOfSep = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 9).Count();
            int AmountOfOct = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 10).Count();
            int AmountOfNov = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 11).Count();
            int AmountOfDec = _context.AdoptionDays.Where(a => a.AdoptionDate.Month == 12).Count();

            Res.Add(AmountOfJan.ToString());
            Res.Add(AmountOfFeb.ToString());
            Res.Add(AmountOfMar.ToString());
            Res.Add(AmountOfApr.ToString());
            Res.Add(AmountOfMay.ToString());
            Res.Add(AmountOfJun.ToString());
            Res.Add(AmountOfJul.ToString());
            Res.Add(AmountOfAug.ToString());
            Res.Add(AmountOfSep.ToString());
            Res.Add(AmountOfOct.ToString());
            Res.Add(AmountOfNov.ToString());
            Res.Add(AmountOfDec.ToString());

            return Json(Res);
        }


    }


}

anypet/Views/AdoptionDays/Create.cshtml
@model AdoptNet.Models.AdoptionDays

@{
    ViewData["Title"] = "Create";
}

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>

<br />
<h1><ins>Adding a new Adoption Day</ins></h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-3 formback">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control " />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control " />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdoptionDate" class="control-label"></label>
                <input asp-for="AdoptionDate" class="form-control" min="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")" max="2050-06-01T00:00" />
                <span asp-validation-for="AdoptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationAdopt" class="control-label"></label>
                <select asp-for="LocationAdopt" class="form-control " asp-items="Html.GetEnumSelectList<Location>()"></select>
                <span asp-validation-for="LocationAdopt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-dark inputspace subotton" />
                <a asp-action="Index"><input value="List" class="btn btn-outline-dark inputspace subotton " /></a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

anypet/Views/AdoptionDays/Delete.cshtml
@model AdoptNet.Models.AdoptionDays

@{ ViewData["Title"] = "Delete"; }

<!-- Button trigger modal -->
<button type="button" data-toggle="modal" data-target="#exampleModal"
        style="margin-left:45%; margin-top: 120px;">
    Delete an Adoption Day
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="column" id="main">
                    <h1 class="deletePopup">
                        Are you sure you want to delete this adoption day?
                    </h1>
                    <br />
                    <dl class="row">
                        <dt class="col-6 mx-auto spacesdes">
                            @Html.DisplayNameFor(model => model.AdoptionDate)
                        </dt>
                        <dd class="col-6 mx-auto spacesdes">
                            @Html.DisplayFor(model => model.AdoptionDate)
                        </dd>
                        <dt class="col-6 mx-auto spacesdes">
                            @Html.DisplayNameFor(model => model.LocationAdopt)
                        </dt>
                        <dd class="col-6 mx-auto spacesdes">
                            @Html.DisplayFor(model => model.LocationAdopt)
                        </dd>
                        <dt class="col-6 mx-auto spacesdes">
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd class="col-6 mx-auto spacesdes">
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt class="col-6 mx-auto spacesdes">
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd class="col-6 mx-auto spacesdes">
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                    </dl>
                    <form asp-action="Delete" style="font-size: .8em;">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-action="Index">Back to List</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

anypet/Views/AdoptionDays/Edit.cshtml
@model AdoptNet.Models.AdoptionDays

@{
    ViewData["Title"] = "Edit";
}

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>

<br />
<h1><ins>Edit an Adoption Day</ins></h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-3 formback">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control " />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdoptionDate" class="control-label"></label>
                <input asp-for="AdoptionDate" id="Adopt" class="form-control" />
                <span asp-validation-for="AdoptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control " />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationAdopt" class="control-label"></label>
                <select asp-for="LocationAdopt" class="form-control " asp-items="Html.GetEnumSelectList<Location>()"></select>
                <span asp-validation-for="LocationAdopt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-outline-dark inputspace subotton" />
                <a asp-action="Index"><input value="List" class="btn btn-outline-dark inputspace subotton " /></a>
            </div>
        </form>
    </div>
</div>



@section Scripts {

    <script src="~/js/fetureofpages.js" asp-append-version="true"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

anypet/Views/AdoptionDays/Index.cshtml
@model IEnumerable<AdoptNet.Models.AdoptionDays>

@{ ViewData["Title"] = "Index"; }

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>

<header class="jumbotron bg-cover text-white image">

    <div class="container py-5 text-center">
        <h2 class="display-4 font-weight-bold">Adoption Days</h2>
    </div>

</header>

@if (ViewContext.HttpContext.User.IsInRole("Association") || ViewContext.HttpContext.User.IsInRole("Admin"))
{
<a asp-action="Create"><input value="Add-AdoptionDay" style="width:160px;" class="btn btn-outline-dark subotton mix" /></a>}

<div style="text-align: center; margin-right: -80px;">
    <form asp-controller="AdoptionDays" asp-action="Search">
        <input name="Searching" placeholder="Enter something to search" />
        <input type="submit" value="Search" class="btn btn-outline-dark subotton"
               style="height:40px; margin-bottom: 15px;" />
    </form>
</div>

<br />

<div class="contin">
    <div class="hero-container">
        @foreach (var adoption in Model)
        {
<div class="main-container">
    <div class="poster-container">
        <a href="#"><img src="~/css/3755878.jpg" class="poster" /></a>
    </div>
    <div class="ticket-container">
        <div class="ticket__content">
            @if (ViewContext.HttpContext.User.IsInRole("Association") || ViewContext.HttpContext.User.IsInRole("Admin"))
            {
<a class="decoText pink" asp-action="Edit" asp-route-id="@adoption.Id">Edit</a><i> | </i>
                    <a class="decoText pink" asp-action="Delete" asp-route-id="@adoption.Id">Delete</a>}
            <h4 class="ticket__movie-title">@adoption.Name</h4>
            <p class="ticket__movie-slogan">
                @adoption.Description
            </p>
            <p class="ticket__current-price">@adoption.AdoptionDate</p>
            <p class="ticket__old-price">@adoption.LocationAdopt</p>
        </div>
    </div>
</div>}
    </div>
</div>