anypet/Models/Animal.cs
using AdoptNet.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace anypet.Models
{


    public enum Size
    {
        [Description("Small")]
        Small,
        [Description("medium")]
        Medium,
        [Description("Big")]
        Big


    }
    public enum Kind
    {
        Dog,
        Cat

    }

    public enum Location
    {
        Center,
        North,
        South
    }
    public enum Gender
    {
       Male,
       Feamle
    }



    //the class itself for the cats,dogs an so on , the details about each pet 
    public class Animal
    {
        public int Id { get; set; }


        [RegularExpression(@"^[a-zA-Z_ ]+$", ErrorMessage = "The name  must contain only letters...")]
        [Required(ErrorMessage = "You must input Name of the Animal")]
        public String Name { get; set; }

        [Display(Name = "species")]
        public Kind Kind { get; set; }


        [RegularExpression("^[0-9]+$", ErrorMessage = "the age is only in numbers ")]
        [Required(ErrorMessage = "You must input Age of the Animal")]
        [Range(0, 110)]
        public uint Age { get; set; }


        //need to check this with validation- maby making it a list of female and male** 
        [Required(ErrorMessage = "You must input the Gender of the Animal")]
        public Gender Gender { get; set; }


        [RegularExpression(@"^[a-zA-Z\s ]+$", ErrorMessage = "The Description must contain only letters...")]
        public String Description { get; set; }


        //need to ne a list of small,medium and big 
        [Required(ErrorMessage = "You must input the Size of the Animal")]
        public Size Size { get; set; }

        [Required(ErrorMessage = "You must input the Location of the Association")]
        public Location Location { get; set; }


        //this field represnt the connection of many to one 
        [Display(Name = "Association")]
        public int AssociationId { get; set; }


        public Association Association { get; set; }


        //this field represent the connection of one to one 
        public AnimalImage AnimalImage { get; set; }


        public Products AnimalProducts { get; set; }








    }
}

anypet/Controllers/AnimalImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using anypet.Models;
using Microsoft.AspNetCore.Authorization;

namespace AdoptNet.Controllers
{
    public class AnimalImagesController : Controller
    {
        private readonly AdoptNetContext _context;
        public AnimalImagesController(AdoptNetContext context)
        {
            _context = context;
        }
        // GET: AnimalImages


        // GET: AnimalImages/Create
        [Authorize(Roles = "Admin,Association")]
        public IActionResult Create()
        {
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name));
            return View();
        }
        // POST: AnimalImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Image,AnimalId")] AnimalImage animalImage)
        {
            if (ModelState.IsValid)
            {
                var check = _context.AnimalImage.Where(r => r.AnimalId.Equals(animalImage.AnimalId));
                if (check.Count() == 0)
                {
                    _context.Add(animalImage);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), "Animals");
                }
                else
                {
                    ViewData["Error"] = "this Animal allready  have an image ";

                }
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), animalImage.AnimalId);
            return View(animalImage);
        }

        // GET: AnimalImages/Edit/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var animalImage = await _context.AnimalImage.FindAsync(id);
            if (animalImage == null)
            {
                return NotFound();
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), animalImage.AnimalId);
            return View(animalImage);
        }
        // POST: AnimalImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Image,AnimalId")] AnimalImage animalImage)
        {
            if (id != animalImage.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(animalImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalImageExists(animalImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Animals");
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), animalImage.AnimalId);
            return View(animalImage);
        }

        // GET: AnimalImages/Delete/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var animalImage = await _context.AnimalImage
                .Include(a => a.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animalImage == null)
            {
                return NotFound();
            }
            return View(animalImage);
        }
        // POST: AnimalImages/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animalImage = await _context.AnimalImage.FindAsync(id);
            _context.AnimalImage.Remove(animalImage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Animals");
        }
        private bool AnimalImageExists(int id)
        {
            return _context.AnimalImage.Any(e => e.Id == id);
        }
    }
}

anypet/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using anypet.Models;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using anypet.Controllers;

namespace AdoptNet.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly AdoptNetContext _context;
        public AnimalsController(AdoptNetContext context)
        {
            _context = context;
        }


        //function for graph 

        public async Task<IActionResult> Search(String Searching)
        {
            var adoptNetContext = (from Al in _context.Animal
                                   join As in _context.Association
                                   on Al.AssociationId equals As.Id
                                   select new Animal
                                   {
                                       Id = Al.Id,
                                       AssociationId = As.Id,
                                       Name = Al.Name,
                                       Kind = Al.Kind,
                                       Age = Al.Age,
                                       Gender = Al.Gender,
                                       Description = Al.Description,
                                       Size = Al.Size,
                                       Location = Al.Location,
                                       AnimalImage = Al.AnimalImage,

                                       Association = As

                                   }
                                   );

            Kind k;
            Location l;
            Gender g;
            Size s;


            Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<anypet.Models.Animal> SearchContent = null;
            if (Searching == null)
            {
                return View("Index", await adoptNetContext.ToListAsync());
            }

            if (Searching.Equals("Cat") || Searching.Equals("Dog"))
            {
                k = (Kind)Enum.Parse(typeof(Kind), Searching);
                SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Kind.Equals(k));

            }
            else if (Searching.Equals("Center") || Searching.Equals("North") || Searching.Equals("South"))
            {
                l = (Location)Enum.Parse(typeof(Location), Searching);
                SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Location.Equals(l));
            }
            else if (Searching.Equals("Male") || Searching.Equals("Female"))
            {
                g = (Gender)Enum.Parse(typeof(Gender), Searching);
                SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Gender.Equals(g));
            }
            else if (Searching.Equals("Small") || Searching.Equals("Medium") || Searching.Equals("Big"))
            {
                s = (Size)Enum.Parse(typeof(Size), Searching);
                SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Size.Equals(s));
            }

            else
            {
               var animals = _context.Animal.Include(a => a.Association).Include(b => b.AnimalImage).Where(b => (b.Name.Contains(Searching) || Searching == null) );
                return View("Index", await animals.ToListAsync());

            }
            if (SearchContent == null)
            {
                return View("Index", new List<Animal>());
            }


            return View("Index", await SearchContent.ToListAsync());
            
            


        }


        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> SearchDog()
        {
            Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<anypet.Models.Animal> SearchContent = null;
            Kind k;

            k = (Kind)Enum.Parse(typeof(Kind), "Dog");
            SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Kind.Equals(k));

            return View("Index", await SearchContent.ToListAsync());
        }


        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> SearchCat()
        {
            Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<anypet.Models.Animal> SearchContent = null;
            Kind k;

            k = (Kind)Enum.Parse(typeof(Kind), "Cat");
            SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Animal>)_context.Animal.Include(x => x.AnimalImage).Include(a => a.Association).Where(a => a.Kind.Equals(k));

            return View("Index", await SearchContent.ToListAsync());
        }


        // GET: Animals
        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> Index()
        {
            var adoptNetContext = (from Al in _context.Animal
                                   join As in _context.Association
                                   on Al.AssociationId equals As.Id
                                   select new Animal
                                   {
                                       Id = Al.Id,
                                       AssociationId = As.Id,
                                       Name = Al.Name,
                                       Kind = Al.Kind,
                                       Age = Al.Age,
                                       Gender = Al.Gender,
                                       Description = Al.Description,
                                       Size = Al.Size,
                                       Location = Al.Location,
                                       AnimalImage = Al.AnimalImage,

                                       Association = As

                                   }
                                   );



            //var adoptNetContext = _context.Animal.Include(a => a.Association).Include(a=>a.AnimalImage);
            return View(await adoptNetContext.ToListAsync());
        }
        // GET: Animals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var animal = await _context.Animal
              .Include(a => a.Association)
            .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }
            return View(animal);
        }

        // GET: Animals/Create
        [Authorize(Roles = "Admin,Association")]
        public IActionResult Create()
        {
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name));
            return View();
        }

        //
        // new part connecting to twitter api
        public static async Task<String> PostMessageToTwitter(string animalName)
        {
            string ConsumerKey = "ArKksYuZtj2RS4MdvZRQtMNBH";
            string ConsumerKeySecret = "XCibkNO5mdsNXNuv114sw9A9HttGUq8wVTy9wOo7l9zfQSL6dn";
            string AccessToken = "1429780751516635138-ANSpo1Rojk9VDOSN4gdzPSeDPPmyAE";
            string AccessTokenSecret = "xsonrP8PHCSE3vy35druX5S62Jx8O4DJKCNfrbKmnqRDO";

            var twitter = new TwitterAPI(ConsumerKey,
                ConsumerKeySecret, AccessToken, AccessTokenSecret);

            string message = "New animal has been added, come in to our website to see " +
                "more about: " + animalName + " and maybe adopt this animal! :-)";

            var response = await twitter.Tweet(message);
            Console.WriteLine(response);

            return response;
        }

        //

        // POST: Animals/Create
        // To protect from overposting attacks, enable the specific properties you want
        // to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Kind,Age,Gender,Description,Size,Location,AssociationId")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(animal);
                await _context.SaveChangesAsync();
                PostMessageToTwitter(animal.Name).Wait();
                return RedirectToAction(nameof(Index));
            }

            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name));
            return View(animal);

        }

        // GET: Animals/Edit/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var animal = await _context.Animal.FindAsync(id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["AssociationId"] = new SelectList(_context.Association, "Id", nameof(Association.Name), animal.AssociationId);
            return View(animal);
        }
        // POST: Animals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

anypet/Views/Animals/Create.cshtml
@model anypet.Models.Animal


@{ ViewData["Title"] = "Create"; }

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">



</head>


<br />
<h1><ins>Adding a new animal</ins></h1>
<hr />
<div class="row justify-content-center ">
    <div class="col-md-3 formback">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control " />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" min="0"/>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kind" class="control-label"></label>
                <select asp-for="Kind" class="form-control " asp-items="Html.GetEnumSelectList<Kind>()"></select>
                <span asp-validation-for="Kind" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control " asp-items="Html.GetEnumSelectList<Gender>()"></select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control " />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <select asp-for="Size" class="form-control " asp-items="Html.GetEnumSelectList<Size>()"></select>
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="Location" class="form-control " asp-items="Html.GetEnumSelectList<Location>()"></select>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="AssociationId" class="control-label"></label>
                <select asp-for="AssociationId" class="form-control" asp-items="ViewBag.AssociationId"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-dark inputspace subotton" />
                <a asp-action="Index"><input value="List" class="btn btn-outline-dark inputspace subotton " /></a>
            </div>
        </form>
    </div>
</div>



 


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

anypet/Views/Animals/Delete.cshtml
@model anypet.Models.Animal

@{ ViewData["Title"] = "Delete"; }

<!-- Button trigger modal -->
<button type="button" data-toggle="modal" data-target="#exampleModal"
        style="margin-left:45%; margin-top: 120px;">
    Delete an animal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="column" id="main">
                    <h1 class="deletePopup">
                        Are you sure you want to delete this animal?
                    </h1>
                    <br />
                    <dl class="row">
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Kind)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Kind)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Age)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Age)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Gender)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Gender)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Size)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Size)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Location)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Location)
                        </dd>
                        <dt class="col-sm-12">
                            @Html.DisplayNameFor(model => model.Association)
                        </dt>
                        <dd class="col-sm-12">
                            @Html.DisplayFor(model => model.Association.Name)
                        </dd>
                    </dl>
                    <form asp-action="Delete" style="font-size: .8em;">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-controller="Animals" asp-action="Index">Back to List</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

anypet/Views/Animals/Index.cshtml
@model IEnumerable<anypet.Models.Animal>



@{ ViewData["Title"] = "Index"; }

<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">


</head>

<header class="jumbotron bg-cover text-white image">

    <div class="container py-5 text-center">
        <h2 class="display-4 font-weight-bold">Animal-Adoption</h2>
    </div>

</header>

@if (ViewContext.HttpContext.User.IsInRole("Association") || ViewContext.HttpContext.User.IsInRole("Admin"))
{
    <a asp-action="Create"><input value="Add-Animal" style="width:120px;" class="btn btn-outline-dark subotton mix" /></a>
}

<div style="text-align: center; margin-right: -80px;">
    <form asp-controller="Animals" asp-action="Search">
        <input name="Searching" placeholder="Enter something to search" />
        <input type="submit" value="Search" class="btn btn-outline-dark subotton"
               style="height:40px; margin-bottom: 15px;" />
    </form>
</div>

<div class="form-group ">

</div>
@foreach (var Animals in Model.GroupBy(x => x.Association.Name))
{
<div class="row">

    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="page-caption">
                        <h3 class="animal-key">
                            @Animals.Key
                        </h3> <!--getting the spefic ID q Key of the animals-->

                    </div>
                </div>
            </div>
        </div>
    </div>


    @foreach (var Animal in Animals)
    {
<div class="col-md-3 ">
    <div class="card spaceCards spceseColor" style="width: 23rem;">

        @if (Animal.AnimalImage != null)
        {
<img src="@Animal.AnimalImage.Image" class="card-img-top" alt="...">}

        <div class="card-body">
            <h3 class="card-title boldt ">@Animal.Name</h3>
            <p class="card-text"> @Animal.Description</p>
            @if (ViewContext.HttpContext.User.IsInRole("Association") || ViewContext.HttpContext.User.IsInRole("Admin"))
            {

<a class="decoText" asp-action="Edit" asp-route-id="@Animal.Id">Edit</a><i>|</i>
                        <a class="decoText" asp-action="Details" asp-route-id="@Animal.Id">Details</a><i>|</i>
                                                <a class="decoText" asp-action="Delete" asp-route-id="@Animal.Id">Delete</a><i>|</i>

                                                @if (Animal.AnimalImage == null)
                       {

                        <a class="decoText" asp-controller="AnimalImages" asp-action="Create">Create Image</a><i>|</i>}


                                                @if (Animal.AnimalImage != null)
                                                {

                        <a class="decoText" asp-controller="AnimalImages" asp-action="Edit" asp-route-id="@Animal.AnimalImage.Id">Edit Image</a><i>|</i>}

                                                                        @if (Animal.AnimalImage != null)
                                                                        {

                                                <a class="decoText" asp-controller="AnimalImages" asp-action="Delete" asp-route-id="@Animal.AnimalImage.Id">Delete Image</a>}}


            <ul class="list-group colorCol list-group-flush">
                <li class="list-group-item list-group-item-danger">Age: @Animal.Age</li>
                <li class="list-group-item list-group-item-danger">Gender: @Animal.Gender</li>
                <li class="list-group-item list-group-item-danger">Size: @Animal.Size</li>
                <li class="list-group-item list-group-item-danger">Location: @Animal.Location</li>
                <li class="list-group-item list-group-item-danger">Kind: @Animal.Kind</li>
                <!--A check to know if the animal belong to association-->
                @if (Animal.Association != null)
                {
<li class="list-group-item list-group-item-danger">Association: @Animal.Association.Name</li>                    }
            </ul>
        </div>

    </div>
</div>}


</div>}