anypet/Controllers/HomeController.cs
using anypet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
namespace anypet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Other()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }





        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

anypet/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using anypet.Models;
using Microsoft.AspNetCore.Authorization;

namespace anypet.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AdoptNetContext _context;

        public ProductsController(AdoptNetContext context)
        {
            _context = context;
        }

        // GET: Products
        [Authorize(Roles = "Admin,Association,Client")]
        public async Task<IActionResult> Index()
        {
            var adoptNetContext = (from As in _context.Products
                                   join im in _context.Animal
                                   on As.AnimalId equals im.Id
                                   select new Products
                                   {
                                       Id = As.Id,
                                       Food = As.Food,
                                       Medicine = As.Medicine,
                                       Toy = As.Toy,
                                       Animal = im,
                                       AnimalId = As.AnimalId
                                   }
                                   );


            //var adoptNetContext = _context.Products.Include(p => p.Animal);
            return View(await adoptNetContext.ToListAsync());
        }







       
        public async Task<IActionResult> Search(String Searching)
        {  // Use LINQ to get list of genres.
            var Products = (from As in _context.Products
                                   join im in _context.Animal
                                   on As.AnimalId equals im.Id
                                   select new Products
                                   {
                                       Id = As.Id,
                                       Food = As.Food,
                                       Medicine = As.Medicine,
                                       Toy = As.Toy,
                                       Animal = im,
                                       AnimalId = As.AnimalId
                                   }
                                  );

            if (!string.IsNullOrEmpty(Searching))
            {                    
                Products = Products.Where(s => s.Toy.Contains(Searching) || s.Medicine.Contains(Searching));
            }       
            
           return View("Index", await Products.ToListAsync());
        }
        


        // GET: Products/Create
        [Authorize(Roles = "Admin,Association")]
        public IActionResult Create()
        {
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name));
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Food,Toy,Medicine,AnimalId")] Products products)
        {
            if (ModelState.IsValid)
            {
                var check = _context.Products.Where(r => r.AnimalId.Equals(products.AnimalId));
                if (check.Count() == 0)
                {
                    _context.Add(products);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["Error"] = "this Animal already  have a Product ";
                }
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), products.AnimalId);
            return View(products);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), products.AnimalId);
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Food,Toy,Medicine,AnimalId")] Products products)
        {
            if (id != products.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", nameof(Animal.Name), products.AnimalId);
            return View(products);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin,Association")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .Include(p => p.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            _context.Products.Remove(products);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

anypet/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdoptNet.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using anypet.Models;

namespace Ad.Controllers
{
    public class UsersController : Controller
    {
        private readonly AdoptNetContext _context;

        public UsersController(AdoptNetContext context)
        {
            _context = context;
        }

        //this isthe get of login & access denied
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        // POST: Users/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Id,Username,Password")] User user) //login func
        {
            if (ModelState.IsValid)
            {
                var q = from u in _context.User
                        where u.Username == user.Username && u.Password == user.Password
                        select u;

                if (q.Count() > 0)
                {

                    Signin(q.First()); //sendind the first user to signin

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "The user's details are incorrect.";
                }
            }
            return View(user);
        }

        private async void Signin(User account)
        {
            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, account.Username),
                    new Claim(ClaimTypes.Role, account.Type.ToString()),
                };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }
        // GET: Users/Register
        public IActionResult Register()
        {
            return View();
        }

        // POST: Users/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Username,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                var q = _context.User.FirstOrDefault(u => u.Username == user.Username); // if return null- there is no user like this ans we can do register


                if (q == null)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    var u = _context.User.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password);

                    Signin(u);

                    return RedirectToAction(nameof(Index), "Home");// regsiter succeed- go to home
                }
                else // user already exists
                {
                    ViewData["Error"] = "The user name is already taken.";
                }
            }
            return View(user);
        }


        public async Task<IActionResult> Logout()
        {
            //HttpContext.Session.Clear();

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Type")] User user)
        {
            if (ModelState.IsValid)
            {
                var q = _context.User.FirstOrDefault(u => u.Username == user.Username); // if return null- there is no user like this ans we can do register

                if (q == null)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                else // user already exists
                {
                    ViewData["Error"] = "This user name is already exist.";
                }
            }
            return View(user);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //// GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }


        //        // POST: Users/Edit/5
        //        // To protect from overposting attacks, enable the specific properties you want to bind to.
        //        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Type")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        public async Task<IActionResult> Search(String Searching)
        {  // Use LINQ to get list of genres.
            Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<anypet.Models.User> SearchContent = null;


            if (Searching.Equals("Client") || Searching.Equals("Admin") || Searching.Equals("Association"))
            {
                UserType k = (UserType)Enum.Parse(typeof(UserType), Searching);
                SearchContent = (Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<User>)_context.User.Where(a => a.Type.Equals(k));

            }
            else
            {
                var user = _context.User.Where(b => (b.Username.Equals(Searching) || Searching == null));
                return View("Index", await user.ToListAsync());

            }


            return View("Index", await SearchContent.ToListAsync());
        }

    }

}

anypet/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }

@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <title>AdoptNet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Product example · Bootstrap v5.0</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

</head>
<body>

    <header class="site-header sticky-top py-1">

        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <!-- link from the logo to home page -->
            <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" aria-label="Product">
                <img src="~/css/Lemonsouce.png" class="bi me-4 px-4" width="150" height="70" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap" />
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center ">
                <li><a asp-controller="Animals" asp-action="index" class="nav-link px-4 text-white ">Animal Adoption</a></li>
                <li><a asp-controller="AdoptionDays" asp-action="Index" class="nav-link px-4 text-white ">Adoption days</a></li>
                <li><a asp-controller="Associations" asp-action="Index" class="nav-link px-4 text-white ">Associations</a></li>
                <li><a asp-controller="Products" asp-action="Index" class="nav-link px-4 text-white ">Animal products</a></li>
                <li><a asp-controller="Home" asp-action="About" class="nav-link px-4 text-white ">About</a></li>
                <li><a asp-controller="Home" asp-action="Other" class="nav-link px-4 text-white ">Other intresting content</a></li>
                @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                {
                 <li><a asp-controller="Users" asp-action="Index" class="nav-link px-4 text-white ">Users Managing</a></li>
                 }
                <form asp-controller="Animals" asp-action="Search">
                    <input name="Searching" placeholder="Enter something to search" />
                    <input type="submit" value="Search" class="btn btn-primary" />
                </form>
                <il class="moving1 ">
                    <il class="text-end px-5 moving1">
                        @if (!(ViewContext.HttpContext.User.IsInRole("Admin") || ViewContext.HttpContext.User.IsInRole("Client") || ViewContext.HttpContext.User.IsInRole("Association")))
                        {
                            <a asp-controller="Users" asp-action="Login"><button type="button" class="btn btn-outline-light me-2 px-3 moving">Login</button></a>
                            <a asp-controller="Users" asp-action="Register"><button type="button" class="btn btn-warning px-3 ">Sign-up</button></a>
                        }

                        @if (ViewContext.HttpContext.User.IsInRole("Admin") || ViewContext.HttpContext.User.IsInRole("Client") || ViewContext.HttpContext.User.IsInRole("Association"))
                        {
                            <a asp-controller="Users" asp-action="Logout"><button type="button" class="btn btn-warning px-3 moving ">Sign-out</button></a>
                        }
                    </il>
            </ul>

        </nav>

    </header>

    <main>

        <video id="video1" preload="" autoplay="" muted="" playsinline="" loop="">
            <source src="~/css/Kittens Meet Puppies For The First Time short video.mp4" type="video/mp4">
        </video>
        <div id="videoMessage" class="styling">
            <h1 class="headline page-title"><br />AdoptNet</h1>
            <h3 class="welcome">
                <b>Hello everyone!</b>
                <br />We are AdoptNet and we are welcoming all of you to our website.
                <br /> As we build AdoptNet our original goal<br /> was to find a way to connect between associations for animals<br /> and people who want to adopt a new friend for life.
                <br /> We work with a number of non-profit organizations in the country<br /> and make it easy for those who want to adopt.
                <br />as we connect  with more and more association and make a collaboration with them <br />the search for a pet gets easier and more accessible
                <br />We wish you a pleasant search and that you will find a new life member.
                <br />AdoptNet Team.

            </h3>

        </div>

        <!--------------------------------------------------------------->

        <div class="b-example-divider"></div>


        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">
                    <a target="_new" href="https://www.medicalnewstoday.com/articles/322868 "><img src="~/css/1.jpeg" class="card-img-top2" alt="..."></a>
                    <div class="card-body">
                        <h3 class="card-title">Dogs: Our best friends in sickness and in health</h3>

                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <a target="_new" href="https://brightside.me/wonder-animals/20-curious-facts-about-pets-thatll-make-you-love-them-even-more-757860/"><img src="~/css/2.jpeg" class="card-img-top2" alt="..."></a>
                    <div class="card-body">
                        <h3 class="card-title">20 Curious Facts About Pets That’ll Make You Love Them</h3>

                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <a target="_new" href="https://pets.webmd.com/features/pets-and-new-baby#1"><img src="~/css/3.jpeg" class="card-img-top2" alt="..."></a>
                    <div class="card-body">
                        <h3 class="card-title">Prepping Your Pet for Your New Baby</h3>

                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <a target="_new" href="https://www.medicalnewstoday.com/articles/322868"><img src="~/css/4 (3).jpeg" class="card-img-top2" alt="..."></a>
                    <div class="card-body">
                        <h3 class="card-title">Dogs: Our best friends in sickness and in health</h3>

                    </div>
                </div>
            </div>
        </div>

        <div class="b-example-divider"></div>

        <div class="bg-dark text-secondary px-4 py-5 text-center">
            <div class="py-5">
                <h1 class="display-5 join">Joining AdoptNet</h1>
                <div class="col-lg-6 mx-auto">
                    <p class="fs-5 mb-4 text">
                        If you are an association that want to join the AdoptNet team please contact us at the number below <br /> 08-9319192 <br />or send an email to: AdoptNet2021@gmail.com
                    </p>
                    <!----
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                        <button type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Custom button</button>
                        <button type="button" class="btn btn-outline-light btn-lg px-4">Secondary</button>
                    </div>
                        -->
                </div>

            </div>
            <div class="container px-5">
                <img src="~/css/ANIMALS.png" class="img-fluid  rounded-3 mb-4" alt="Example image" width="700" height="500" loading="lazy">
            </div>
        </div>

        <div class="b-example-divider mb-0"></div>

        <!------------------navbarside-->



    </main>

    <!-- the DIV that will contain the widget -->
    <div class="weatherWidget"></div>

    <script>
        window.weatherWidgetConfig = window.weatherWidgetConfig || [];
        window.weatherWidgetConfig.push({
            selector: ".weatherWidget",
            apiKey: "QE6RQD4H9DX3UKN2Z7MM3ZSDJ", //Sign up for your personal key
            location: "Tel Aviv, ISR", //Enter an address
            unitGroup: "metric", //"us" or "metric"
            forecastDays: 5, //how many days forecast to show
            title: "Weather in Tel Aviv, Israel", //optional title to show in the
            showTitle: true,
            showConditions: true
        });

        (function () {
            var d = document, s = d.createElement('script');
            s.src = 'https://www.visualcrossing.com/widgets/forecast-simple/weather-forecast-widget-simple.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>

    <div class="b-example-divider"></div>


    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Adoption Days</h3>
                        <ul>
                            <li><a asp-action="Index" asp-controller="AdoptionDays">Adoption Days</a></li>
                            <li><a asp-action="SearchDog" asp-controller="Animals">Adopt Dog</a></li>
                            <li><a asp-action="SearchCat" asp-controller="Animals">Adopt Cat</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a asp-action="About" asp-controller="Home">About Us</a></li>
                            <li>Contact us: 08-9319192</li>
                            <li>AdoptNet Email:AdoptNet2021@gmail.com </li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>AdpotNet website</h3>
                        <p>
                            As we build AdoptNet our original goal
                            was to find a way to connect between associations for animals
                            and people who want to adopt a new friend for life.
                            We work with a number of non-profit organizations in the country
                            and make it easy for those who want to adopt.
                            as we connect with more and more association and make a collaboration with them
                            the search for a pet gets easier and more accessible
                            We wish you a pleasant search and that you will find a new life member.
                            AdoptNet Team.
                        </p>
                    </div>
                    <div class="col item social">
                        <a href="https://www.facebook.com/AdoptNet">
                            <i class="icon ion-social-facebook"></i>
                        </a>
                        <a href="https://www.instagram.com/adopt_net/?utm_medium=copy_link">
                            <i class="icon ion-social-instagram"></i>
                        </a>
                        <a href="https://twitter.com/NetAdopt">
                            <i class="icon ion-social-twitter"></i>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>


</body>
</html>